name = "Postal"
uuid = "281d7c9c-f17a-4237-a411-dffb7e66d385"
authors = ["Matt Bhagat-Conway <matt@indicatrix.org> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
